// ===== PACKAGES DATA =====
export const packages = [
  {
    id: "basic",
    name: "Basic",
    price: 100000,
    priceLabel: "Rp 100.000",
    period: "/bulan",
    color: "blue",
    gradient: "from-blue-600 to-blue-800",
    borderColor: "border-blue-500/40",
    glowColor: "rgba(14,165,233,0.3)",
    waGroup: "https://chat.whatsapp.com/basic-group",
    features: [
      "Akses sinyal saham harian",
      "Berita pasar realtime",
      "Chart IHSG",
      "Modul dasar investasi",
      "Grup WA Basic",
    ],
    description: "Cocok untuk pemula yang ingin mulai berinvestasi saham dengan panduan dasar.",
  },
  {
    id: "silver",
    name: "Silver",
    price: 250000,
    priceLabel: "Rp 250.000",
    period: "/bulan",
    color: "cyan",
    gradient: "from-cyan-600 to-blue-700",
    borderColor: "border-cyan-500/40",
    glowColor: "rgba(34,211,238,0.3)",
    waGroup: "https://chat.whatsapp.com/silver-group",
    features: [
      "Semua fitur Basic",
      "Analisis fundamental saham",
      "Screening saham bagger",
      "Risk & money management",
      "Grup WA Silver",
    ],
    description: "Untuk investor yang ingin memahami fundamental dan mulai screening saham potensial.",
  },
  {
    id: "gold",
    name: "Gold",
    price: 500000,
    priceLabel: "Rp 500.000",
    period: "/bulan",
    color: "gold",
    gradient: "from-yellow-500 to-orange-600",
    borderColor: "border-yellow-500/40",
    glowColor: "rgba(245,158,11,0.3)",
    popular: true,
    waGroup: "https://chat.whatsapp.com/gold-group",
    features: [
      "Semua fitur Silver",
      "Sinyal entry, antri, TP, SL premium",
      "Analisis teknikal mendalam",
      "Modul psikologi & emosi trading",
      "Potensi saham multi-bagger",
      "Grup WA Gold Eksklusif",
    ],
    description: "Paket terlaris! Lengkap dengan sinyal premium dan panduan psikologi trading.",
  },
  {
    id: "pro",
    name: "Pro",
    price: 750000,
    priceLabel: "Rp 750.000",
    period: "/bulan",
    color: "purple",
    gradient: "from-purple-600 to-indigo-700",
    borderColor: "border-purple-500/40",
    glowColor: "rgba(147,51,234,0.3)",
    waGroup: "https://chat.whatsapp.com/pro-group",
    features: [
      "Semua fitur Gold",
      "AI Agent trading assistant",
      "Watchlist saham personal",
      "Laporan mingguan eksklusif",
      "Priority support",
      "Grup WA Pro VIP",
    ],
    description: "Dilengkapi AI Agent personal untuk bantu analisis dan keputusan trading Anda.",
    hasAI: true,
  },
  {
    id: "platinum",
    name: "Platinum",
    price: 900000,
    priceLabel: "Rp 900.000",
    period: "/bulan",
    color: "platinum",
    gradient: "from-slate-400 to-slate-600",
    borderColor: "border-slate-400/40",
    glowColor: "rgba(148,163,184,0.3)",
    waGroup: "https://chat.whatsapp.com/platinum-group",
    features: [
      "Semua fitur Pro",
      "AI Agent canggih + analisis portofolio",
      "Konsultasi 1-on-1 dengan analis",
      "Akses semua modul VIP",
      "Sinyal real-time 24/7",
      "Grup WA Platinum Elite",
    ],
    description: "Pengalaman investasi terdepan dengan AI Agent canggih dan konsultasi personal.",
    hasAI: true,
  },
  {
    id: "elite",
    name: "Elite",
    price: 1000000,
    priceLabel: "Rp 1.000.000",
    period: "/bulan",
    color: "elite",
    gradient: "from-yellow-400 via-yellow-500 to-orange-500",
    borderColor: "border-yellow-400/60",
    glowColor: "rgba(251,191,36,0.5)",
    waGroup: "https://chat.whatsapp.com/elite-group",
    features: [
      "Semua fitur Platinum",
      "AI Agent Elite terdepan",
      "Portofolio management personal",
      "Akses mentor langsung",
      "Event & webinar eksklusif",
      "Grup WA Elite Master",
      "Laporan harian personal",
    ],
    description: "Paket paling eksklusif. Mentoring langsung, AI Agent Elite, dan akses penuh semua fitur.",
    hasAI: true,
    isElite: true,
  },
];

// ===== MODULES DATA =====
export const vipModules = [
  {
    id: "fundamental",
    title: "Analisis Fundamental",
    icon: "📊",
    description: "Pelajari cara membaca laporan keuangan, rasio valuasi, dan menilai kesehatan perusahaan.",
    content: [
      { title: "Membaca Laporan Keuangan", desc: "Cara analisis neraca, laba rugi, dan arus kas perusahaan publik Indonesia." },
      { title: "Rasio Valuasi", desc: "PER, PBV, EV/EBITDA, dan rasio penting lainnya untuk menilai harga wajar saham." },
      { title: "Analisis Manajemen", desc: "Menilai track record manajemen, corporate governance, dan transparansi." },
      { title: "Analisis Industri", desc: "Memahami siklus industri, competitive advantage, dan posisi perusahaan." },
    ],
  },
  {
    id: "bagger",
    title: "Saham Bagger",
    icon: "🚀",
    description: "Strategi menemukan saham multi-bagger yang bisa naik 2x-10x dalam jangka menengah-panjang.",
    content: [
      { title: "Kriteria Saham Bagger", desc: "Karakteristik saham yang berpotensi menjadi multi-bagger: growth, moat, dan timing." },
      { title: "Screening Saham", desc: "Teknik screening menggunakan fundamental dan teknikal untuk menemukan calon bagger." },
      { title: "Entry & Exit Strategy", desc: "Kapan waktu yang tepat masuk dan keluar dari posisi untuk maksimalkan return." },
      { title: "Case Study", desc: "Analisis saham-saham yang sudah terbukti menjadi multi-bagger di BEI." },
    ],
  },
  {
    id: "potensi",
    title: "Saham Potensial",
    icon: "💡",
    description: "Identifikasi sektor dan saham yang memiliki potensi pertumbuhan tinggi ke depan.",
    content: [
      { title: "Analisis Makro", desc: "Pengaruh kondisi makroekonomi terhadap pergerakan saham dan sektor." },
      { title: "Sektor Unggulan", desc: "Sektor-sektor yang memiliki prospek cerah di pasar modal Indonesia." },
      { title: "Thematic Investing", desc: "Investasi berbasis tema besar: EV, energi hijau, infrastruktur, digital." },
      { title: "Watchlist Premium", desc: "Daftar saham potensial yang dipantau dan dianalisis secara berkala." },
    ],
  },
  {
    id: "risk",
    title: "Risk Management",
    icon: "🛡️",
    description: "Kelola risiko investasi dengan strategi yang terstruktur dan disiplin.",
    content: [
      { title: "Definisi & Jenis Risiko", desc: "Memahami berbagai jenis risiko: market risk, liquidity risk, dan company risk." },
      { title: "Stop Loss Strategy", desc: "Cara menetapkan dan mematuhi stop loss untuk proteksi modal." },
      { title: "Diversifikasi Portofolio", desc: "Strategi diversifikasi yang efektif tanpa over-diversifikasi." },
      { title: "Position Sizing", desc: "Menentukan ukuran posisi yang tepat berdasarkan risiko dan modal." },
    ],
  },
  {
    id: "money",
    title: "Money Management",
    icon: "💰",
    description: "Kelola modal investasi dengan bijak untuk pertumbuhan jangka panjang yang konsisten.",
    content: [
      { title: "Alokasi Modal", desc: "Strategi alokasi modal: berapa persen untuk setiap posisi dan sektor." },
      { title: "Dollar Cost Averaging", desc: "Teknik DCA untuk mengurangi risiko timing dan rata-rata harga beli." },
      { title: "Reinvestasi Profit", desc: "Cara mengelola profit: kapan reinvestasi, kapan ambil keuntungan." },
      { title: "Emergency Fund", desc: "Pentingnya dana darurat sebelum berinvestasi dan cara menghitungnya." },
    ],
  },
  {
    id: "emosi",
    title: "Emosi & Psikologi",
    icon: "🧠",
    description: "Kuasai aspek psikologi trading — faktor terbesar yang membedakan trader sukses dan gagal.",
    content: [
      { title: "Fear & Greed", desc: "Mengenali dan mengelola rasa takut dan serakah dalam keputusan investasi." },
      { title: "FOMO & Panic Selling", desc: "Cara menghindari FOMO dan panic selling yang sering merugikan investor." },
      { title: "Trading Journal", desc: "Pentingnya mencatat setiap transaksi untuk evaluasi dan perbaikan." },
      { title: "Mindset Investor", desc: "Membangun mindset jangka panjang dan disiplin dalam berinvestasi." },
    ],
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Budi Santoso",
    package: "Gold",
    avatar: "BS",
    rating: 5,
    text: "Sinyalnya akurat banget! Dalam 2 bulan porto gua naik 35%. Komunitas juga aktif dan supportif.",
    date: "Mei 2025",
  },
  {
    id: 2,
    name: "Sari Dewi",
    package: "Platinum",
    avatar: "SD",
    rating: 5,
    text: "AI Agent-nya luar biasa, bisa analisis saham kapan aja. Mentor juga responsif dan helpful banget.",
    date: "April 2025",
  },
  {
    id: 3,
    name: "Rizky Pratama",
    package: "Silver",
    avatar: "RP",
    rating: 5,
    text: "Modul fundamental-nya komprehensif. Sekarang udah bisa analisis sendiri tanpa bingung.",
    date: "Maret 2025",
  },
  {
    id: 4,
    name: "Diana Putri",
    package: "Elite",
    avatar: "DP",
    rating: 5,
    text: "Worth every penny! Sinyal elite + mentor langsung bikin return gua konsisten tiap bulan.",
    date: "Februari 2025",
  },
  {
    id: 5,
    name: "Ahmad Fauzi",
    package: "Pro",
    avatar: "AF",
    rating: 5,
    text: "AI Agent Pro bisa bantu watchlist dan ingatkan sinyal. Fiturnya nambah terus, mantap!",
    date: "Januari 2025",
  },
];
